name: ðŸ§ª

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

env: ${{ secrets }}

jobs:
  only-changed:
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.diff.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find projects which have changed
        uses: ./.github/actions/diff
        id: diff

  test:
    runs-on: ubuntu-latest
    needs: only-changed

    # should have at least one project to run (cannot have empty matrix)
    if: fromJSON(needs.only-changed.outputs.projects)[0] != null

    strategy:
      matrix:
        project: ${{ fromJSON(needs.only-changed.outputs.projects) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          project: ${{ matrix.project }}

      - name: Run tests
        working-directory: ${{ matrix.project }}
        run: npm run test --if-present

      - name: Try build
        working-directory: ${{ matrix.project }}
        run: npm run build --if-present
